name: Minecraft AFK Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual runs from GitHub UI
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 00:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install mineflayer

      - name: 🚀 Run Minecraft bot
        run: node bot.js
